# Generated by Django 3.2.7 on 2021-09-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0002_auto_20210924_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='new note', max_length=200),
        ),
    ]
